#!/usr/bin/perl
#This routine mark up n nearest molecules of the atom range [$ido $ide
if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help' || $ARGV[0] eq '--help')
{
help();
exit;
}
sub help {
  print "\n=== mark_nextnearest_n - Multiple Nearest Neighbor Selection ===\n\n";
  print "PURPOSE:\n";
  print "  Iteratively marks the N nearest molecules to a range of atoms. Each iteration\n";
  print "  finds the next-closest unmarked molecule and marks it.\n\n";
  print "USAGE:\n";
  print "  mark_nextnearest_n atom_id_start atom_id_end N mark_val file.pxyz\n\n";
  print "PARAMETERS:\n";
  print "  atom_id_start  - First atom ID in search range (1-based indexing)\n";
  print "  atom_id_end    - Last atom ID in search range (1-based indexing, inclusive)\n";
  print "  N              - Number of molecules to mark\n";
  print "  mark_val       - Mark value to assign to nearest molecules\n";
  print "  file.pxyz      - Input .pxyz file (REQUIRED as argument)\n\n";
  print "INPUT:\n";
  print "  - .pxyz file specified as argument (NOT via stdin)\n\n";
  print "OUTPUT:\n";
  print "  - **MODIFIES INPUT FILE DIRECTLY** - use with caution!\n";
  print "  - Prints progress information to stdout\n\n";
  print "DETAILS:\n";
  print "  - Calls mark_nextnearest N times to mark N closest molecules\n";
  print "  - Each iteration finds the next-closest unmarked molecule\n";
  print "  - Uses 1-based indexing for atom IDs\n";
  print "  - **WARNING**: This script modifies the input file in-place\n";
  print "  - Always work with backup copies of important data\n";
  print "  - Useful for building QM fitting regions with specific numbers of molecules\n\n";
  print "EXAMPLES:\n";
  print "  cp system.pxyz backup.pxyz\n";
  print "  mark_nextnearest_n 1 25 5 3 system.pxyz    # Mark 5 nearest molecules as QM fitting\n";
  print "  mark_nextnearest_n 50 75 3 2 temp.pxyz     # Add 3 molecules to QM buffer\n\n";
  print "SEE ALSO:\n";
  print "  mark_nextnearest  - Mark single nearest molecule\n\n";
}


$ido=$ARGV[0];shift; #This is the first atom id of the seleted molecule
$ide=$ARGV[0];shift; #Last atom id of the selected molecule
$nmark=$ARGV[0];shift; #Number of Molecules to be Marked. 
$val=$ARGV[0];shift; #mark value
$filename=$ARGV[0];

for ($i=0;$i<$nmark;$i++)
{
$cmd="mark_nextnearest $ido $ide $val $filename > $filename._$$; mv $filename._$$ $filename";
print "mark_nextnearest $ido $ide $val $filename\n";
#print $cmd."\n";
system("$cmd");
}
